# Generated by config...
cpp=cc -E
cc=cc
intr_ld=ld
ld=cc
shell=/bin/sh
cppargs=-Wall
ccargs=-g -Wall -c -fpic
intr_ldargs=-r
ldargs=-shared
includearg=-I
definearg=-D
libarg=-l
outputarg=-o
preargs=
includes=common/include
defines=NULL=0
libs=m
incb=`for include in $(includes); do echo -n " $(includearg) $$include ";done`
defb=`for define in $(defines); do echo -n " $(definearg) $$define "; done`
libb=`for lib in $(libs); do echo -n " $(libarg) $$lib "; done`
cext=.c
cppext=.i
objext=.o
mainobj=main.o
bin=lib/libsweer.so
prefix=/usr/
libdir=lib
headerdir=include
sourcedirs=common
tccbuildf=sweer.pjr
header=include/sweer.h
cfiles=`for dir in $(sourcedirs); do echo -n " $$dir/*$(cext) "; done`
cppfiles=`for dir in $(sourcedirs); do echo -n " $$dir/*$(cppext) "; done`
objfiles=`for dir in $(sourcedirs); do echo -n " $$dir/*$(objext) "; done`

all: clean makebdir
	if [ -f $(tccbuildf) ]; then rm $(tccbuildf); fi

	for file in $(cfiles); do \
		echo $$file >> $(tccbuildf); \
		echo $(cpp) $(cppargs) $(incb) $(defb) \
			"$$file" $(outputarg) "$$file$(cppext)" | tee /dev/stderr | sh; \
		if test $$? -ne "0"; then\
			exit 1;\
		fi;\
	done

	for file in $(cppfiles); do \
		echo $(cc) $(ccargs) "$$file" $(outputarg) "$$file$(objext)" \
			| tee /dev/stderr | sh; \
		if test "$$?" -ne "0"; then\
			exit 1;\
		fi;\
	done

	for file in $(objfiles); do \
		if test -f "$(mainobj)"; then \
			echo $(intr_ld) $(intr_ldargs) "$$file" "$(mainobj)" $(outputarg) \
				"$(mainobj).tmp.o" | tee /dev/stderr | sh; \
		else \
			cp "$$file" "$(mainobj).tmp.o"; \
		fi; \
		if test "$$?" -ne "0"; then \
			exit 1; \
		fi; \
		mv "$(mainobj).tmp.o" "$(mainobj)"; \
	done

	$(ld) $(libb) $(ldargs) $(mainobj) $(outputarg) $(bin)

clean:
	if [ -f "$(mainobj)" ]; then rm $(mainobj); fi
	if [ -f "$(bin)" ]; then rm $(bin); fi
	for file in  $(cppfiles) $(objfiles); do\
                 if [ -f $$file ]; then rm "$$file"; fi; done

makebdir:
	if [ ! -d lib ]; then mkdir lib; fi

install: all
	cp $(bin) $(prefix)$(libdir)
	cp $(header) $(prefix)$(headerdir)
